# Generated by Django 4.1.7 on 2023-03-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='tip_next',
            field=models.TextField(null=True),
        ),
    ]
