# Generated by Django 4.1.7 on 2023-03-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_rename_tip_next_puzzle_tip_this'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='tip_this',
            new_name='tip_next',
        ),
    ]
