# Generated by Django 4.1.7 on 2023-03-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_rename_tip_next_puzzle_tip_this'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='tip_this',
            field=models.TextField(blank=True, null=True),
        ),
    ]
